on: 
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

name: CMake

jobs:
  cmake-build:
    name: CMake ${{ matrix.os }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        build_type: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@master

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}      

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'Build.zip'
        path: ${{ github.workspace }}
        directory: ${{ github.workspace }}/build
        
    - name: Release to GitHub
      uses: softprops/action-gh-release@v2
      with:
        body: "Upstreamed to [ZTzTopia/ENet](https://github.com/ZTzTopia/ENet)"
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        tag_name: workflow_${{ github.run_number }}
        name: Release ${{ matrix.os }} - ${{ github.run_number }}
        make_latest: true
        files: |
           ${{ github.workspace }}/Build.zip
